user: 
    first_name: Firstname
    last_name: Lastname
    github_username: github_username
    email: email@email.com
    x_handle: x_handle
    avatar_url: null
    link: https://github.com/github_username
    force_avatar_key: x_handle

database:
    use_engine: postgresql
    
    postgres:
        db_name: heat_battery
        user: postgres
        password: workflow_password
        host: 127.0.0.1
        port: 5432
        bin_files_folder_prefix: ./heat_battery_data/
