user: 
    username: Github Actions

database:
    use_engine: postgresql
    
    postgres:
        db_name: heat_battery
        user: postgres
        password: dummy_password
        host: 127.0.0.1
        port: 5432
        bin_files_folder_prefix: ./heat_battery_data/
