from geometry_v7 import build_geometry

build_geometry(
    name='mesh',
    dir=".",
    verbosity=4,
    fltk=['premesh', 'postmesh'],
    #symmetry=False,
    size=1,
    mesh_size_max=0.1,
    t_insulation=1.0,
    mesh_size_from_curvature=18,
    cartridge_n=10, 
    cartridge_d_ratio=0.5,
    cartridge_diameter=0.014,
    cartridge_h_ratio=0.9,
    cartridge_spreader_lb=0.02  ,
    cartridge_spreader_nb=3,
    cartridge_spreader_tb=0.005,
    cartridge_spreader_mesh_size_min=0.003,
    cartridge_spreader_mesh_grow_factor=0.8,
    tht_in_sand=True,
    tht_d=0.04,
    tht_d_ratio=0.1,
    tht_n_ratio=0.6,
    thp_mesh_size_min=0.0025,
    thp_mesh_grow_factor=0.8,
    tht_spreader_h_ratio=0.9,
    tht_spreader_lb=0.06,
    tht_spreader_nb=3,
    tht_spreader_tb=0.005,
    thp_spreader_mesh_size_min=0.0025,
    thp_spreader_mesh_grow_factor=0.8,
    thp_surface_segments=10,
    sand_material="SandTheory",
    insulation_material="Standard_insulation",
    thp_spreader_material="Steel04",
    cartridge_material="Steel04",
    cartridge_spreader_material="Steel04",
)