# This workflow is equivalent to build-ubuntu.yml but for WSL

name: WSL-Ubuntu 

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: Vampire/setup-wsl@v3
      with:
         distribution: Ubuntu-22.04
         update: 'true'

    - uses: actions/checkout@v4
    
    - name: Check Python3 version and add pip3
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: |
        python3 --version
        sudo apt -y install python3-pip
    
    - name: Install and test OpenMPI
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: | 
        sudo apt-get update
        sudo apt install -y build-essential 
        sudo apt-get -y install openmpi-bin openmpi-doc libopenmpi-dev
        pip3 install mpi4py
        mpirun -n 1 --allow-run-as-root python3 -c "from mpi4py import MPI; print(f'rank: {MPI.COMM_WORLD.rank}')"

    - name: Install and test gmsh
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: |
        sudo apt -y install gmsh
        pip3 install gmsh
        python3 -c "import gmsh"

    - name: Install FeniCSx
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: | 
        sudo add-apt-repository -y ppa:fenics-packages/fenics
        sudo apt-get update
        sudo apt install -y fenicsx
        echo "Install finnished!!"

    - name: Test dolfinx import
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: python3 -c "import dolfinx; from dolfinx import __version__; print(f'Python is OK, dolfinx version {__version__}')"

    - name: Install, start and configure PostgreSQL server
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: |
        sudo apt install -y postgresql postgresql-contrib libpq-dev
        sudo service postgresql start
        sudo pg_isready
        sudo -u postgres psql template1 -c "ALTER USER postgres with encrypted password 'dummy_password';"
        sudo pg_isready
  
    - name: Install HeatBattery via setup.py
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: |
        pip3 install .
        python3 -c "import heat_battery; print('heat_battery imported successfully!')"

    - name: Show version of installed packages
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: pip3 freeze

    - name: Show files in dist-packages for heat_battery
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: |
        PY_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1-2)
        echo "Files in /usr/local/lib/python${PY_VERSION}/dist-packages/heat_battery/*:"
        if [ -d "/usr/local/lib/python${PY_VERSION}/dist-packages/heat_battery" ]; then
          ls -l /usr/local/lib/python${PY_VERSION}/dist-packages/heat_battery/*
        else
          echo "Directory not found"
        fi

    - name: Show files in site-packages for heat_battery
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: |
        USERNAME=$(whoami)
        PY_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1-2)
        echo "Files in /home/${USERNAME}/.local/lib/python${PY_VERSION}/site-packages/heat_battery/*:"
        if [ -d "/home/${USERNAME}/.local/lib/python${PY_VERSION}/site-packages/heat_battery" ]; then
          ls -l /home/${USERNAME}/.local/lib/python${PY_VERSION}/site-packages/heat_battery/*
        else
          echo "Directory not found"
        fi

    - name: Report free memory before cache clear
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: free -h

    - name: Test with unittest and record coverage
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: python3 examples/run.py --example="Example_01"