# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Ubuntu 

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Update system packages
      run: | 
        sudo apt update
        sudo apt upgrade
        sudo apt install build-essential
        sudo apt install git cmake

    #postgresql-14=14.15-0ubuntu0.22.04.1
    - name: Install, start and configure PostgreSQL server
      run: |
        sudo apt list --installed | grep postgresql-14
        sudo apt install postgresql-14 postgresql-contrib
        sudo apt install acl
        sudo systemctl start postgresql.service
        sudo pg_isready
        sudo -u postgres psql template1 -c "ALTER USER postgres with encrypted password 'dummy_password';"
        sudo pg_isready
        psql --version
        sudo apt list --installed | grep postgresql-plpython3-14 || echo "first grep postgresql-plpython3-14 exited with 1"
        sudo apt install postgresql-plpython3=14.15-1.pgdg22.04+1
        sudo apt list --installed | grep postgresql-plpython3-14 || echo "second grep postgresql-plpython3-14 exited with 1"
        sudo setfacl -Rm u:postgres:rwx,u:$(whoami):rwx ./heat_battery_data/
        sudo setfacl -Rdm u:postgres:rwx,u:$(whoami):rwx ./heat_battery_data/

    - name: Install and test OpenMPI
      run: | 
        sudo apt install openmpi-bin openmpi-doc libopenmpi-dev
        pip3 install mpi4py
        mpirun -n 1 python3 -c "from mpi4py import MPI; print(f'rank: {MPI.COMM_WORLD.rank}')"

    - name: Check Python3 version
      run: |
        python3 --version
        which python3

    - name: Install and test gmsh
      run: |
        sudo apt install gmsh
        pip3 install gmsh
        python3 -c "import gmsh"

    - name: Install FeniCSx
      run: | 
        sudo add-apt-repository ppa:fenics-packages/fenics
        sudo apt update
        sudo apt install fenicsx
        echo "Install finnished!!"

    - name: Install ADIOS2 from source  
      run: |
        org_wd=$(pwd)
        git clone https://github.com/ornladios/ADIOS2.git ADIOS2
        mkdir build-adios2
        cd build-adios2
        cmake ../ADIOS2 -DADIOS2_BUILD_EXAMPLES=ON
        make -j $(nproc)
        sudo make install
        sudo ldconfig
        cd $org_wd
        rm -rf ADIOS2
        rm -rf build-adios2

    - name: Show files in dist-packages for adios2 in python3.x
      run: |
        PY_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1-2)
        echo "Files in /usr/local/lib/python${PY_VERSION}/dist-packages/:"
        if [ -d "/usr/local/lib/python${PY_VERSION}/dist-packages" ]; then
          ls -l /usr/local/lib/python${PY_VERSION}/dist-packages/*
        else
          echo "Directory not found"
        fi

    - name: Show files in site-packages for adios2 in python3.x
      run: |
        USERNAME=$(whoami)
        PY_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1-2)
        echo "Files in /home/${USERNAME}/.local/lib/python${PY_VERSION}/site-packages/:"
        if [ -d "/home/${USERNAME}/.local/lib/python${PY_VERSION}/site-packages" ]; then
          ls -l /home/${USERNAME}/.local/lib/python${PY_VERSION}/site-packages/*
        else
          echo "Directory not found"
        fi

    - name: Show files in dist-packages for adios2 in python3
      run: |

        echo "Files in /usr/local/lib/python3/dist-packages/:"
        if [ -d "/usr/local/lib/python3/dist-packages/" ]; then
          ls -l /usr/local/lib/python3/dist-packages/*
        else
          echo "Directory not found"
        fi

    - name: Show files in site-packages for adios2 in python3
      run: |
        USERNAME=$(whoami)
        echo "Files in /home/${USERNAME}/.local/lib/python3/site-packages/:"
        if [ -d "/home/${USERNAME}/.local/lib/python3/site-packages" ]; then
          ls -l /home/${USERNAME}/.local/lib/python3/site-packages/*
        else
          echo "Directory not found"
        fi

    - name: Check if ADIOS2 python bindings are misplaced in local/local/lib instead of local/lib
      run: |
        PY_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1-2)
        echo "Files in /usr/local/local/lib/python${PY_VERSION}/dist-packages/adios2"
        if [ -d "/usr/local/local/lib/python${PY_VERSION}/dist-packages/adios2" ]; then
          ls -l /usr/local/local/lib/python${PY_VERSION}/dist-packages/adios2/*
          echo "Creating directory /usr/local/lib/python${PY_VERSION}/dist-packages/adios2"
          sudo mkdir -p /usr/local/lib/python${PY_VERSION}/dist-packages/adios2
          echo "Copying files to /usr/local/lib/python${PY_VERSION}/dist-packages/adios2"
          sudo cp -r /usr/local/local/lib/python${PY_VERSION}/dist-packages/adios2/* /usr/local/lib/python${PY_VERSION}/dist-packages/adios2/
          sudo ldconfig
          echo "List other packages that might be present in the wrong directory:"
          ls -l /usr/local/local/lib/python${PY_VERSION}/dist-packages/*
        else
          echo "Directory not found"
        fi

    - name: Test adios2 import
      run: |
        python3 -c "import adios2"

    - name: Test dolfinx import
      run: python3 -c "import dolfinx; from dolfinx import __version__; print(f'Python is OK, dolfinx version {__version__}')"

    - name: Install HeatBattery via setup.py
      run: |
        pip3 install .
        python3 -c "import heat_battery; print('heat_battery imported successfully!')"

    - name: Show version of installed packages
      run: pip3 freeze

    - name: Install coverage.py
      run: pip3 install coverage

    - name: Show files in dist-packages for heat_battery
      run: |
        PY_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1-2)
        echo "Files in /usr/local/lib/python${PY_VERSION}/dist-packages/heat_battery/*:"
        if [ -d "/usr/local/lib/python${PY_VERSION}/dist-packages/heat_battery" ]; then
          ls -l /usr/local/lib/python${PY_VERSION}/dist-packages/heat_battery/*
        else
          echo "Directory not found"
        fi

    - name: Show files in site-packages for heat_battery
      run: |
        USERNAME=$(whoami)
        PY_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1-2)
        echo "Files in /home/${USERNAME}/.local/lib/python${PY_VERSION}/site-packages/heat_battery/*:"
        if [ -d "/home/${USERNAME}/.local/lib/python${PY_VERSION}/site-packages/heat_battery" ]; then
          ls -l /home/${USERNAME}/.local/lib/python${PY_VERSION}/site-packages/heat_battery/*
        else
          echo "Directory not found"
        fi

    - name: Report free memory
      run: free -h

    - name: Test with unittest and record coverage
      run: coverage run --source="./heat_battery" -m unittest discover -v -s ./test  -p 'test_*.py'

    - name: Show coverage report
      run: >
        echo "Code coverage: $(coverage report -m | grep 'TOTAL'| grep -o '[0-9]*%')"
