# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: WSL-Ubuntu 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: Vampire/setup-wsl@v3
      with:
         distribution: Ubuntu-22.04
         update: 'true'

    - uses: actions/checkout@v4
    
    - name: Check Python3 version
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: python3 --version
    
    - name: Install and test OpenMPI
      shell: wsl-bash_Ubuntu-22.04 {0}
      run: | 
        sudo apt-get update
        sudo apt install build-essential
        sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
        pip3 install mpi4py
        mpirun -n 1 python3 -c "from mpi4py import MPI; print(f'rank: {MPI.COMM_WORLD.rank}')"

    - name: Install and test gmsh
      run: |
        sudo apt install gmsh
        pip3 install gmsh
        python3 -c "import gmsh"

    - name: Install FeniCSx
      run: | 
        sudo add-apt-repository ppa:fenics-packages/fenics
        sudo apt-get update
        sudo apt install fenicsx
        echo "Install finnished!!"

    - name: Test dolfinx import
      run: python3 -c "import dolfinx; from dolfinx import __version__; print(f'Python is OK, dolfinx version {__version__}')"

    - name: Install HeatBattery via setup.py
      run: |
        pip3 install .
        python3 -c "import heat_battery; print('heat_battery imported successfully!')"

    - name: Show version of installed packages
      run: pip3 freeze

    - name: Test with unittest 
      run: python3 -m unittest discover -v -s ./test  -p 'test_*.py'