# This workflow is equivalent to build-ubuntu.yml but for WSL

name: WSL-Ubuntu 

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
    - uses: actions/checkout@v4
    
    - name: Initialize WSL
      shell: powershell
      run: |
        wsl --install --no-distribution
        wsl --update
        wsl --install -d Ubuntu-22.04 --no-launch
        wsl --set-default Ubuntu-22.04
        wsl --list --verbose
        
    - name: Check Python3 version and add pip3
      run: |
        python3 --version
        sudo apt -y install python3-pip
    
    - name: Install and test OpenMPI
      run: | 
        sudo apt-get update
        sudo apt install -y build-essential 
        sudo apt-get -y install openmpi-bin openmpi-doc libopenmpi-dev
        pip3 install mpi4py
        mpirun -n 1 --allow-run-as-root python3 -c "from mpi4py import MPI; print(f'rank: {MPI.COMM_WORLD.rank}')"

    - name: Install and test gmsh
      run: |
        sudo apt -y install gmsh
        pip3 install gmsh
        python3 -c "import gmsh"

    - name: Install FeniCSx
      run: | 
        sudo add-apt-repository -y ppa:fenics-packages/fenics
        sudo apt-get update
        sudo apt install -y fenicsx
        echo "Install finnished!!"

    - name: Test dolfinx import
      run: python3 -c "import dolfinx; from dolfinx import __version__; print(f'Python is OK, dolfinx version {__version__}')"

    - name: Install, start and configure PostgreSQL server
      run: |
        sudo apt install -y postgresql postgresql-contrib libpq-dev
        sudo service postgresql start
        sudo pg_isready
        sudo -u postgres psql template1 -c "ALTER USER postgres with encrypted password 'dummy_password';"
        sudo pg_isready
  
    - name: Install HeatBattery via setup.py
      run: |
        pip3 install .
        python3 -c "import heat_battery; print('heat_battery imported successfully!')"

    - name: Show version of installed packages
      run: pip3 freeze

    - name: Install coverage.py
      run: pip3 install coverage

    - name: Test with unittest and record coverage
      run: coverage run --source="./heat_battery" -m unittest discover -v -s ./test  -p 'test_*.py'

    - name: Show coverage report
      run: >
        echo "Code coverage: $(coverage report -m | grep 'TOTAL'| grep -o '[0-9]*%')"