name: Count lines of code

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  count_lines_of_code:

    runs-on: ubuntu-22.04
   
    steps:
    - uses: actions/checkout@v4

    - name: Install cloc
      run: |
        sudo apt-get install cloc

    - name: Count lines of code
      id: cloc
      run: |
        cloc_output=$(cloc . --sum-one --quiet --fullpath --not-match-d="heat_battery/visualization/assets/(lotties|images)" | grep SUM)
        cloc_blank_lines=$(echo "$cloc_output" | awk '{print $3}')
        echo "blank lines: $cloc_blank_lines"
        cloc_comments_lines=$(echo "$cloc_output" | awk '{print $4}')
        echo "comments lines: $cloc_comments_lines"
        cloc_code_lines=$(echo "$cloc_output" | awk '{print $5}')
        echo "code lines: $cloc_code_lines"
        cloc_total_lines=$(($cloc_blank_lines + $cloc_comments_lines + $cloc_code_lines))
        echo "total lines: $cloc_total_lines"
        echo "cloc_blank_lines=$cloc_blank_lines" >> "$GITHUB_OUTPUT"
        echo "cloc_comments_lines=$cloc_comments_lines" >> "$GITHUB_OUTPUT"
        echo "cloc_code_lines=$cloc_code_lines" >> "$GITHUB_OUTPUT"
        echo "cloc_total_lines=$cloc_total_lines" >> "$GITHUB_OUTPUT"
        echo "cloc_total_lines_human=$(numfmt --to=si $cloc_total_lines)" >> "$GITHUB_OUTPUT"
        echo "cloc_blank_lines_human=$(numfmt --to=si $cloc_blank_lines)" >> "$GITHUB_OUTPUT"
        echo "cloc_comments_lines_human=$(numfmt --to=si $cloc_comments_lines)" >> "$GITHUB_OUTPUT"
        echo "cloc_code_lines_human=$(numfmt --to=si $cloc_code_lines)" >> "$GITHUB_OUTPUT"


    - name: Create badge for lines of code
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 6f402d08683e16acdfc545b806f60259
        filename: cloc-ubuntu-22.04.json
        label: Lines of code
        message: "${{ steps.cloc.outputs.cloc_code_lines_human }}/${{ steps.cloc.outputs.cloc_total_lines_human }}"
        color: green

