name: Refresh cloc history cache and chart

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upload-gist:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - name: Install cloc and python dependencies
        run: |
          sudo apt-get install cloc
          pip3 install plotly
          pip3 install -U kaleido
          pip3 install pandas

      - name: Pull clocl cache file
        run: |
          GIST_URL="https://gist.githubusercontent.com/LiborKudela/6f402d08683e16acdfc545b806f60259/raw/cloc_history_cache.csv"
          curl -s -o cloc_history_cache.csv $GIST_URL || curl -o cloc_history_cache.csv $GIST_URL 
          
      - name: Make install script executable
        run: chmod +x utilities/update_cloc_data.sh

      - name: Update cloc history data
        run: |
          bash utilities/update_cloc_data.sh cloc_history_cache.csv

      - name: Upload new cloc history data cache to gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_SECRET }}
          FILE_PATH: cloc_history_cache.csv
          GIST_ID: "6f402d08683e16acdfc545b806f60259"
        run: |
          CONTENT=$(jq -Rs '.' < "$FILE_PATH")
          echo "{\"files\": {\"$(basename $FILE_PATH)\": {\"content\": $CONTENT}}}" > payload.json
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GIST_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/gists/$GIST_ID" \
            -d @payload.json
          rm payload.json

      - name: Create SVG chart files
        run: |
          python3 "utilities/create_cloc_chart.py" cloc_history_cache.csv
          

      - name: Upload new SVG to Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_SECRET }}
          FILE_PATH: cloc_history_cache.svg
          GIST_ID: "6f402d08683e16acdfc545b806f60259"
        run: |
          CONTENT=$(jq -Rs '.' < "$FILE_PATH")
          echo "{\"files\": {\"$(basename $FILE_PATH)\": {\"content\": $CONTENT}}}" > payload.json
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GIST_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/gists/$GIST_ID" \
            -d @payload.json
          rm payload.json
