name: Upload SVG to Gist

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  upload-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cloc and python dependencies
        run: |
          sudo apt-get install cloc
          sudo apt-get install gh
          pip3 install plotly
          pip3 install -U kaleido
          pip3 install pandas

      - name: Pull and update cloc history data
        run: |
          GIST_URL="https://gist.githubusercontent.com/LiborKudela/6f402d08683e16acdfc545b806f60259/raw/cloc_history_cache.csv" || echo "failed to load cache file from gists: cloc_history_cache.csv"
          curl -o cloc_history_cache.csv $GIST_URL
          bash utilities/update_cloc_data.sh cloc_history_cache.csv

      - name: Upload new cloc history data cache to gist
        run: |
          gh auth login --with-token < ${{ secrets.GIST_SECRET }}
          gh gist edit 6f402d08683e16acdfc545b806f60259 --add cloc_history_cache.csv

      - name: Create SVG chart files
        run: |
          python3 "utilities/create_cloc_chart.py" cloc_history_cache.csv

      - name: Upload new SVG to Gist
        run: |
          gh auth login --with-token < ${{ secrets.GIST_SECRET }}
          gh gist edit 6f402d08683e16acdfc545b806f60259 --add cloc_history_cache.svg
