name: Ubuntu 22.04 install

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
permissions:
  contents: read

env:
  TRY_POSTGRESQL_PPA: true

jobs:
  install_and_unittest:

    runs-on: ubuntu-22.04
   
    steps:
    - uses: actions/checkout@v4

    - name: Create virtual environment
      run: |
        sudo apt install python3-venv
        python3 -m venv --system-site-packages hb_venv

    - name: Make install script executable
      run: chmod +x install_scripts/install_ubuntu.sh

    - name: Install script
      run: |
        source hb_venv/bin/activate
        config_ppass=$(cat .github/github_test_config.yaml | grep -oP '(?<=password: )[^ ]+')
        config_ppassc=$(echo ${config_ppass})
        config_hbdir=$(cat .github/github_test_config.yaml | grep -oP '(?<=bin_files_folder_prefix: )[^ ]+')
        bash install_scripts/install_ubuntu.sh -y -p --ppass ${config_ppass} --ppassc ${config_ppassc} --hbdir ${config_hbdir}

    - name: Install coverage
      run: |
        source hb_venv/bin/activate
        pip3 install coverage

    - name: Run unittest
      run: |
        source hb_venv/bin/activate
        python3 -m coverage run --source="./heat_battery" -m unittest discover -v -s ./test  -p 'test_*.py'

    - name: Coverage report
      id: coverage
      run: |
        source hb_venv/bin/activate
        coverage_report=$(python3 -m coverage report -m | grep 'TOTAL'| grep -o '[0-9]*')
        echo "Code coverage: ${coverage_report}%"
        echo "{coverage}={$coverage_report}" >> "$GITHUB_OUTPUT"
    
    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 6f402d08683e16acdfc545b806f60259
        filename: coverage-ubuntu-22.04.json
        label: Coverage
        message: ${{ steps.coverage.outputs.coverage }}%
        color: ${{ steps.coverage.outputs.coverage >= 80 && 'green' || steps.coverage.outputs.coverage >= 70 && 'yellow' || 'red' }}
