name: Ubuntu 24.04 install and unittest

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
permissions:
  contents: read

env:
  TRY_POSTGRESQL_PPA: true

jobs:
  install_and_unittest:

    runs-on: ubuntu-24.04
   
    steps:
    - uses: actions/checkout@v4

    - name: Set build badge to "in progress"
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 6f402d08683e16acdfc545b806f60259
        filename: success-build-ubuntu-24.04.json
        label: build
        message: "in progress"
        color: yellow

    - name: Set unittest badge to "in progress"
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 6f402d08683e16acdfc545b806f60259
        filename: success-unittest-ubuntu-24.04.json
        label: Test
        message: "in progress"
        color: yellow

    - name: Set disk usage badge to "in progress"
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 6f402d08683e16acdfc545b806f60259
        filename: disk-usage-ubuntu-24.04.json
        label: Disk usage
        message: "in progress"
        color: yellow

    - name: Store initial disk space
      run: echo avail_df[$(date '+%d.%m.%Y %H:%M:%S')]=$(df . --output=avail | tail -n 1) > vminfo.initial

    - name: Create virtual environment
      run: |
        sudo apt install python3-venv
        python3 -m venv --system-site-packages hb_venv

    - name: Make install script executable
      run: chmod +x install_scripts/install_ubuntu.sh

    - name: Install script
      run: |
        source hb_venv/bin/activate
        config_ppass=$(cat .github/github_test_config.yaml | grep -oP '(?<=password: )[^ ]+')
        config_ppassc=$(echo ${config_ppass})
        config_hbdir=$(cat .github/github_test_config.yaml | grep -oP '(?<=bin_files_folder_prefix: )[^ ]+')
        bash install_scripts/install_ubuntu.sh -y -p --ppass ${config_ppass} --ppassc ${config_ppassc} --hbdir ${config_hbdir}

    - name: Set build badge to "Failing" if install script fails
      if: failure()
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 6f402d08683e16acdfc545b806f60259
        filename: success-build-ubuntu-24.04.json
        label: build
        message: "failing"
        color: red
  
    - name: Set build badge to "Succes" if install script completes without errors
      if: success()
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 6f402d08683e16acdfc545b806f60259
        label: build
        filename: success-build-ubuntu-24.04.json
        message: "success"
        color: green

    - name: Install coverage
      run: |
        source hb_venv/bin/activate
        pip3 install coverage

    - name: Run unittest
      run: |
        source hb_venv/bin/activate
        python3 -m coverage run --source="./heat_battery" -m unittest discover -v -s ./test  -p 'test_*.py'

    - name: Create success unittest badge
      if: success()
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 6f402d08683e16acdfc545b806f60259
        filename: success-unittest-ubuntu-24.04.json
        label: Test
        message: "passing"
        color: green
  
    - name: Set unittest badge to "Failing" if unittest fails
      if: failure()
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 6f402d08683e16acdfc545b806f60259
        filename: success-unittest-ubuntu-24.04.json
        label: Test
        message: "failing"
        color: red

    - name: Coverage report
      id: coverage
      run: |
        source hb_venv/bin/activate
        coverage_report=$(python3 -m coverage report -m | grep 'TOTAL' | awk '{print $NF}' | sed 's/%//')
        echo "Code coverage: ${coverage_report}%"
        echo "coverage=$coverage_report" >> "$GITHUB_OUTPUT"
      
    - name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 6f402d08683e16acdfc545b806f60259
        filename: coverage-ubuntu-22.04.json
        label: Code coverage
        message: "${{ steps.coverage.outputs.coverage }}%"
        color: ${{ steps.coverage.outputs.coverage >= 80 && 'green' || steps.coverage.outputs.coverage >= 70 && 'yellow' || 'red' }}

    - name: Report of disk usage
      id: disk_space_consumed
      run: |
        echo avail_df[$(date '+%d.%m.%Y %H:%M:%S')]=$(df . --output=avail | tail -n 1) > vminfo.final
        initial_avail_space=$(cat vminfo.initial | grep '^avail_df' | sed 's/.*=\s*\(.*\)/\1/')
        echo "Initial avail space: $initial_avail_space"
        final_avail_space=$(cat vminfo.final | grep '^avail_df' | sed 's/.*=\s*\(.*\)/\1/')
        echo "Final avail space: $final_avail_space"
        consumed_space_raw=$(($initial_avail_space - $final_avail_space))
        echo "Consumed space raw: $consumed_space_raw"
        consumed_space_human=$(numfmt --to=si $(($consumed_space_raw*1000))) || echo "Failed to convert to human readable space"
        echo "Consumed space human readable: $consumed_space_human"
        echo "disk_space_consumed=$consumed_space_human" >> "$GITHUB_OUTPUT"

    - name: Create disk space badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 6f402d08683e16acdfc545b806f60259
        filename: disk-usage-ubuntu-24.04.json
        label: Disk usage
        message: "${{ steps.disk_space_consumed.outputs.disk_space_consumed }}"
        color: green
