name: Ubuntu 20.04 install

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
permissions:
  contents: read

env:
  TRY_POSTGRESQL_PPA: true

jobs:
  install_and_unittest:

    runs-on: ubuntu-20.04
   
    steps:
    - uses: actions/checkout@v4

    - name: Store initial disk space
      run: echo avail_df[$(date '+%d.%m.%Y %H:%M:%S')]=$(df . --output=avail | tail -n 1) > vminfo.initial

    - name: Make install script executable
      run: chmod +x install_scripts/install_ubuntu.sh

    - name: Install script
      run: |
        config_ppass=$(cat .github/github_test_config.yaml | grep -oP '(?<=password: )[^ ]+')
        config_ppassc=$(echo ${config_ppass})
        config_hbdir=$(cat .github/github_test_config.yaml | grep -oP '(?<=bin_files_folder_prefix: )[^ ]+')
        bash install_scripts/install_ubuntu.sh -y -p --ppass ${config_ppass} --ppassc ${config_ppassc} --hbdir ${config_hbdir}

    - name: Install coverage
      run: pip3 install coverage

    - name: Run unittest
      run: |
        python3 -m coverage run --source="./heat_battery" -m unittest discover -v -s ./test  -p 'test_*.py'

    - name: Coverage report
      run: >
        echo "Code coverage: $(python3 -m coverage report -m | grep 'TOTAL'| grep -o '[0-9]*%')"

    - name: Report of disk usage
      run: |
        initial_avail_space=$(cat vminfo.initial | grep '^avail_df' | sed 's/.*=\s*\(.*\)/\1/')
        echo "Initial avail space: $initial_avail_space"
        final_avail_space=$(cat vminfo.final | grep '^avail_df' | sed 's/.*=\s*\(.*\)/\1/')
        echo "Final avail space: $final_avail_space"
        consumed_space_raw=$(($initial_avail_space - $final_avail_space))
        echo "Consumed space raw: $consumed_space_raw"
        consumed_space_human=$(numfmt --to=si $(($consumed_space_raw*1000))) || echo "Failed to convert to human readable space"
        echo "Consumed space human: $consumed_space_human"